In [8]:
import  numpy as np
from function import *

### 激活函数ReLu的实现
$
ReLu=\begin{cases}
x & x>0 \\
0 & x<=0 \\
\end{cases}$

In [2]:
class Relu:
    def __init__(self):
        self.mark = None
    def forward(self, x):
        self.mark = x<=0
        out = x.copy()
        out[self.mark] = 0
        return out
    def backward(self, dout):
        dout[self.mark] = 0
        dx = dout
        return dx


In [5]:
x = np.array([[1.0,0.5],[-2.0,3.0]])
x<=0

array([[False, False],
       [ True, False]])

### sigmoid层的实现
$ sigmoid = \frac{1}{1+exp(-x)}$

In [6]:
class Sigmoid:
    def __init__(self):
        self.out = None
    def forward(self, x):
        out = 1/(1+np.exp(-x))
        self.out = out
        return  out
    def backward(self,dout):
        dx = dout*(1.0-self.out)*self.out
        return dx

In [7]:
class Affine:
    def __init__(self, w, b):
        self.w = w
        self.b = b
        self.x = None
        self.dw = None
        self.db = None
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.w)+self.b
        return out
    def backward(self,dout):
        dx = np.dot(dout, self.w.T)
        self.dw = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        return dx

In [16]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        return self.loss
    def backforward(self, dout = 1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t)/batch_size
        return dx

In [22]:
temp = SoftmaxWithLoss()
x = np.array([[0.3,0.6,0.1],[0.2,0.2,0.8]])
t = np.array([[0,0,1],[0,0,1]])

loss = temp.forward(x,t)
temp.backforward(1)


array([[ 0.15779892,  0.21300626, -0.37080517],
       [ 0.13081749,  0.13081749, -0.26163499]])

array([[ 0.15779892,  0.21300626, -0.37080517],
       [ 0.13081749,  0.13081749, -0.26163499]])