In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5,3)
x

tensor([[0.5234, 0.8903, 0.1754],
        [0.3086, 0.3729, 0.2169],
        [0.6010, 0.0754, 0.5078],
        [0.1070, 0.6584, 0.8469],
        [0.8423, 0.7806, 0.1284]])

In [4]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x = torch.Tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [6]:
#根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.5855, 0.7570, 0.2010],
        [0.2794, 0.9470, 0.1850],
        [0.7295, 0.6472, 0.9526],
        [0.8987, 0.4931, 0.9583],
        [0.5898, 0.0505, 0.3077]])


In [7]:
x.size()

torch.Size([5, 3])

In [8]:
y = torch.rand(5,3)
print(y+x)
print(torch.add(x, y))

tensor([[1.3283, 1.1914, 0.3666],
        [1.2681, 1.6211, 0.4639],
        [1.5742, 0.8994, 1.7054],
        [1.7590, 0.6674, 1.2384],
        [1.1076, 0.1027, 1.2429]])
tensor([[1.3283, 1.1914, 0.3666],
        [1.2681, 1.6211, 0.4639],
        [1.5742, 0.8994, 1.7054],
        [1.7590, 0.6674, 1.2384],
        [1.1076, 0.1027, 1.2429]])


In [9]:
# 提供输出tensor作为参数
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3283, 1.1914, 0.3666],
        [1.2681, 1.6211, 0.4639],
        [1.5742, 0.8994, 1.7054],
        [1.7590, 0.6674, 1.2384],
        [1.1076, 0.1027, 1.2429]])


In [10]:
#任何 以``_`` 结尾的操作都会用结果替换原变量.
y.add_(x)
y

tensor([[1.3283, 1.1914, 0.3666],
        [1.2681, 1.6211, 0.4639],
        [1.5742, 0.8994, 1.7054],
        [1.7590, 0.6674, 1.2384],
        [1.1076, 0.1027, 1.2429]])

In [11]:
x[:,]

tensor([[0.5855, 0.7570, 0.2010],
        [0.2794, 0.9470, 0.1850],
        [0.7295, 0.6472, 0.9526],
        [0.8987, 0.4931, 0.9583],
        [0.5898, 0.0505, 0.3077]])

In [12]:
# torch.view: 可以改变张量的维度和大小
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [13]:
# Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [14]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a.add_(1)
print(b)

[2. 2. 2. 2. 2.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out= a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
x = torch.randn(1000,1000)

In [18]:
# 所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到 NumPy 的转换.
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([[ 2.0047, -1.1578,  2.2934,  ...,  1.5786, -0.1117,  1.1788],
        [ 2.9665,  2.2422,  1.7742,  ...,  2.2433,  0.1254,  1.8226],
        [ 1.8942,  0.8489,  1.8689,  ...,  0.9646,  0.6464, -0.3662],
        ...,
        [ 0.7655, -0.4733,  0.8977,  ...,  0.8139, -0.6237, -0.1851],
        [ 0.8395,  2.3474,  2.9089,  ...,  2.5486, -1.6350,  0.9559],
        [ 2.0138,  1.8968,  0.5009,  ...,  2.1168,  0.6904,  2.0379]],
       device='cuda:0')
tensor([[ 2.0047, -1.1578,  2.2934,  ...,  1.5786, -0.1117,  1.1788],
        [ 2.9665,  2.2422,  1.7742,  ...,  2.2433,  0.1254,  1.8226],
        [ 1.8942,  0.8489,  1.8689,  ...,  0.9646,  0.6464, -0.3662],
        ...,
        [ 0.7655, -0.4733,  0.8977,  ...,  0.8139, -0.6237, -0.1851],
        [ 0.8395,  2.3474,  2.9089,  ...,  2.5486, -1.6350,  0.9559],
        [ 2.0138,  1.8968,  0.5009,  ...,  2.1168,  0.6904,  2.0379]],
       dtype=torch.float64)
