In [2]:
import torch
import torch.nn as nn

In [6]:
Linear_one = nn.Linear(5,1,bias=True)
x = torch.randn(3,5)
Linear_one(x)

tensor([[1.7408],
        [1.2946],
        [0.9395]], grad_fn=<AddmmBackward>)

In [9]:
list(Linear_one.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-0.3403, -0.3724, -0.1910, -0.3679, -0.3603]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.3179], requires_grad=True))]