In [129]:
import torch
import torch.nn as nn

In [130]:
class Model(nn.Module):
    def __init__(self,ndim):
        super(Model,self).__init__()
        self.ndim = ndim
        self.weight = nn.Parameter(torch.randn(ndim,1))
        self.bias = nn.Parameter(torch.randn(1))
    def forward(self,x):
        return x.mm(self.weight) + self.bias


In [154]:
f = Model(5)
data = torch.randn(3,5)
data,f(data)

(tensor([[-0.3881,  0.5622, -1.5338, -0.6530,  1.7952],
         [ 1.2101,  0.8145, -0.4427,  1.5764, -0.3484],
         [-1.2987,  0.7560,  0.5950,  1.6613, -0.7202]]),
 tensor([[-0.3103],
         [ 0.3733],
         [ 0.6641]], grad_fn=<AddBackward0>))

In [132]:
list(f.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-1.3630],
          [ 1.1085],
          [-0.0539],
          [-0.3535],
          [ 0.4077]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([-0.0339], requires_grad=True))]

In [133]:
f.cuda()
list(f.parameters())

[Parameter containing:
 tensor([[-1.3630],
         [ 1.1085],
         [-0.0539],
         [-0.3535],
         [ 0.4077]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([-0.0339], device='cuda:0', requires_grad=True)]

In [134]:
t1 = torch.randn(3,4,requires_grad=True)
t1

tensor([[-0.1171, -0.5964,  0.1782,  0.5529],
        [ 0.9731, -0.7841, -0.9198,  0.0919],
        [-0.4664, -1.1399, -0.0901, -0.4642]], requires_grad=True)

In [135]:
t2 = t1.sum()
t2

tensor(-2.7820, grad_fn=<SumBackward0>)

In [136]:
with torch.no_grad():
    t2 = t1.sum()
    t2

In [137]:
t2

tensor(-2.7820)

In [139]:
t1.sum(),t1.sum().detach()

(tensor(-2.7820, grad_fn=<SumBackward0>), tensor(-2.7820))

In [147]:
t1 = torch.randn(5,requires_grad=True)
t2 = torch.randn(5,requires_grad=True)
Mse = nn.MSELoss()
t1,t2,Mse(t1,t2)

(tensor([ 0.8212,  0.0810, -0.8491, -2.3750, -0.6127], requires_grad=True),
 tensor([ 1.4719, -0.7438,  0.6076, -0.5703,  0.3520], requires_grad=True),
 tensor(1.4827, grad_fn=<MseLossBackward>))

In [153]:
t1 = torch.randn(5,10,requires_grad=True)
t2 = torch.randint(0,10,(5,))
cross = nn.CrossEntropyLoss()
t1,t2,cross(t1,t2)

(tensor([[ 3.6414e-01, -1.1698e-01, -3.1765e-01, -1.0818e+00,  2.0205e-01,
           1.0316e+00,  1.6758e-01, -7.5532e-04,  2.6735e-01,  1.0588e+00],
         [-7.8210e-01, -2.2516e-01,  5.7616e-01, -8.1745e-02, -5.7181e-01,
           1.3745e-01, -1.9697e-01,  8.0099e-02,  1.1420e-01,  4.7388e-02],
         [ 1.7632e+00, -1.1096e+00, -4.4155e-01, -1.6864e+00, -1.9406e+00,
          -3.1044e-01,  7.5462e-01, -1.2871e+00, -5.4319e-01,  1.4365e+00],
         [ 7.4471e-01,  6.2845e-02, -1.4989e+00,  1.0193e+00, -3.2780e-01,
           8.5275e-01, -8.2926e-01,  1.7788e-01,  1.0199e+00,  2.1847e-01],
         [-2.2736e-01,  1.8530e+00, -2.4837e-01, -1.0563e+00,  1.2216e+00,
           6.0198e-02, -1.3090e+00,  1.2300e+00,  1.6030e-01,  9.2170e-01]],
        requires_grad=True),
 tensor([6, 6, 4, 9, 7]),
 tensor(2.7673, grad_fn=<NllLossBackward>))