In [1]:
import torch

In [2]:
a  = torch.ones((3,2))
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [3]:
x = torch.eye(5,5)
x.new_zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
x = torch.randn(3,3,device='cuda:0')
x.device

device(type='cuda', index=0)

In [5]:
x = x.cpu()
x.device
x = x.cuda(0)
x.device

device(type='cuda', index=0)

In [6]:
print(x.shape)
print(x.size())
# print(x.view(1,-1))
print(x.data_ptr,x.view(1,9).data_ptr)

torch.Size([3, 3])
torch.Size([3, 3])
<built-in method data_ptr of Tensor object at 0x00000289738D8CC8> <built-in method data_ptr of Tensor object at 0x00000289738DF688>


In [7]:
x,x.max(-1)

(tensor([[-1.8636, -1.0689, -0.9224],
         [-0.5398,  0.2517, -0.9596],
         [ 0.5677, -0.3610, -0.0455]], device='cuda:0'),
 torch.return_types.max(
 values=tensor([-0.9224,  0.2517,  0.5677], device='cuda:0'),
 indices=tensor([2, 1, 0], device='cuda:0')))

In [8]:
t1 = torch.randn(3,4)
t2 = torch.randn(3,4)
t3 = torch.randn(3,4)
t4 = torch.randn(3,2)

In [9]:
t1,t2,t3

(tensor([[-0.5291,  1.2467, -0.8162,  0.3413],
         [ 0.2377,  0.5647, -1.1754, -0.5825],
         [-0.1641, -1.3494, -0.2904, -2.6672]]),
 tensor([[ 2.4000,  0.0631,  0.9667, -0.2470],
         [ 0.9334, -0.1718,  1.4099, -0.7701],
         [ 0.2211,  0.3295, -1.5076, -0.8000]]),
 tensor([[-0.1156, -1.0504, -0.1598, -0.1879],
         [-0.4930, -0.8169, -0.1404,  0.8201],
         [-0.5145, -1.0097, -0.3850,  1.0979]]))

In [10]:
t1.ndimension(),torch.stack([t1,t2,t3],1)

(2,
 tensor([[[-0.5291,  1.2467, -0.8162,  0.3413],
          [ 2.4000,  0.0631,  0.9667, -0.2470],
          [-0.1156, -1.0504, -0.1598, -0.1879]],
 
         [[ 0.2377,  0.5647, -1.1754, -0.5825],
          [ 0.9334, -0.1718,  1.4099, -0.7701],
          [-0.4930, -0.8169, -0.1404,  0.8201]],
 
         [[-0.1641, -1.3494, -0.2904, -2.6672],
          [ 0.2211,  0.3295, -1.5076, -0.8000],
          [-0.5145, -1.0097, -0.3850,  1.0979]]]))

In [11]:
torch.cat([t1,t2,t3],-1)

tensor([[-0.5291,  1.2467, -0.8162,  0.3413,  2.4000,  0.0631,  0.9667, -0.2470,
         -0.1156, -1.0504, -0.1598, -0.1879],
        [ 0.2377,  0.5647, -1.1754, -0.5825,  0.9334, -0.1718,  1.4099, -0.7701,
         -0.4930, -0.8169, -0.1404,  0.8201],
        [-0.1641, -1.3494, -0.2904, -2.6672,  0.2211,  0.3295, -1.5076, -0.8000,
         -0.5145, -1.0097, -0.3850,  1.0979]])

In [42]:
x = torch.randn(3,10)
x,x.max(1)

(tensor([[-1.3888,  0.9773,  1.5808, -0.8999, -0.0387,  1.6684,  1.0894, -1.5779,
           0.2512, -0.3409],
         [ 0.3629, -0.3850,  0.3795, -0.2220,  0.6631,  0.3088,  2.1291, -0.0434,
          -0.1849, -0.3213],
         [ 0.3321,  0.6361,  0.5239, -0.0194,  1.2731, -0.0492, -0.4647, -0.8944,
           0.6950, -0.4806]]),
 torch.return_types.max(
 values=tensor([1.6684, 2.1291, 1.2731]),
 indices=tensor([5, 6, 4])))

In [49]:
_,predicted = x.max(1)
predicted
target = torch.zeros(3)
# target[4] = 1
target.size()
# predicted
predicted.eq(target).sum().item()

0