In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
z = y * y
t = torch.mean(z)
z,t

(tensor([[9., 9.],
         [9., 9.]], grad_fn=<MulBackward0>),
 tensor(9., grad_fn=<MeanBackward0>))

In [5]:
t.backward()

In [6]:
x.grad,y.grad,z.grad

d:\study\pythonstudy\pycharmprojects\deeplearn\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


(tensor([[1.5000, 1.5000],
         [1.5000, 1.5000]]),
 None,
 None)

In [20]:
a = torch.arange(9,dtype=torch.float)
torch.norm(a),sum(a**2),torch.sqrt(sum(a**2))

(tensor(14.2829), tensor(204.), tensor(14.2829))

In [26]:
torch.linalg.norm(a,None)

tensor(14.2829)

In [9]:
b = a.reshape(3,3)
b.norm(),b.norm(p="nuc")

(tensor(14.2829), tensor(15.4919))

In [10]:
b,b.norm(dim=1),b.size(),b.norm(dim=1).size(),b.norm(dim=0,p=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 tensor([ 2.2361,  7.0711, 12.2066]),
 torch.Size([3, 3]),
 torch.Size([3]),
 tensor([ 9., 12., 15.]))

In [11]:
x = torch.ones(3,requires_grad=True)
y = x * 2
y = y*2
y

tensor([4., 4., 4.], grad_fn=<MulBackward0>)

In [12]:
v = torch.tensor([1,1,3],dtype=torch.float)
y.backward(v)


In [13]:
x.grad

tensor([ 4.,  4., 12.])

In [14]:
x = torch.ones(3,dtype=torch.float,requires_grad=True)
y = x + 2
z = y * x
z

tensor([3., 3., 3.], grad_fn=<MulBackward0>)

In [15]:
z.backward(v)

In [16]:
x.grad,y.grad,v

d:\study\pythonstudy\pycharmprojects\deeplearn\venv\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


(tensor([ 4.,  4., 12.]), None, tensor([1., 1., 3.]))

In [17]:
input = torch.ones(4)
w1 = torch.tensor(2.0,requires_grad=True)
w2 = torch.tensor(3.0,requires_grad=True)
w3 = torch.tensor(4.0,requires_grad=True)
input,w1,w2,w3


(tensor([1., 1., 1., 1.]),
 tensor(2., requires_grad=True),
 tensor(3., requires_grad=True),
 tensor(4., requires_grad=True))