In [1]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
print(y.grad_fn)


In [5]:
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
# .requires_grad_( ... ) 可以改变现有张量的 requires_grad属性。
# 如果没有指定的话，默认输入的flag是 False。
a = torch.randn(2,2)
a = (a*3/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [7]:
out
# print(out.backward())

tensor(27., grad_fn=<MeanBackward0>)

In [8]:
out.backward()

In [9]:
import numpy as np
import torch

num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.from_numpy(np.random.normal(0, 1, (num_examples,
num_inputs)))
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] +true_b
labels += torch.from_numpy(np.random.normal(0, 0.01,
size=labels.size()))

In [10]:
features.shape

torch.Size([1000, 2])

In [11]:
labels.shape

torch.Size([1000])